// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.3
// source: bus.proto

package proto_bus

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type BusService struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Fservice:
	//	*BusService_ShareRide
	//	*BusService_Deliver
	Fservice isBusService_Fservice `protobuf_oneof:"fservice"`
}

func (x *BusService) Reset() {
	*x = BusService{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bus_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BusService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusService) ProtoMessage() {}

func (x *BusService) ProtoReflect() protoreflect.Message {
	mi := &file_bus_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusService.ProtoReflect.Descriptor instead.
func (*BusService) Descriptor() ([]byte, []int) {
	return file_bus_proto_rawDescGZIP(), []int{0}
}

func (m *BusService) GetFservice() isBusService_Fservice {
	if m != nil {
		return m.Fservice
	}
	return nil
}

func (x *BusService) GetShareRide() *BusService_ShareRideSerivce {
	if x, ok := x.GetFservice().(*BusService_ShareRide); ok {
		return x.ShareRide
	}
	return nil
}

func (x *BusService) GetDeliver() *BusService_DeliverSerivce {
	if x, ok := x.GetFservice().(*BusService_Deliver); ok {
		return x.Deliver
	}
	return nil
}

type isBusService_Fservice interface {
	isBusService_Fservice()
}

type BusService_ShareRide struct {
	ShareRide *BusService_ShareRideSerivce `protobuf:"bytes,1,opt,name=share_ride,json=shareRide,proto3,oneof"`
}

type BusService_Deliver struct {
	Deliver *BusService_DeliverSerivce `protobuf:"bytes,2,opt,name=deliver,proto3,oneof"`
}

func (*BusService_ShareRide) isBusService_Fservice() {}

func (*BusService_Deliver) isBusService_Fservice() {}

type Bus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BusId          string        `protobuf:"bytes,1,opt,name=bus_id,json=busId,proto3" json:"bus_id,omitempty"`
	DelayTime      int32         `protobuf:"varint,2,opt,name=delay_time,json=delayTime,proto3" json:"delay_time,omitempty"`
	ServiceNum     int32         `protobuf:"varint,3,opt,name=service_num,json=serviceNum,proto3" json:"service_num,omitempty"`
	ReasonId       int32         `protobuf:"varint,4,opt,name=reason_id,json=reasonId,proto3" json:"reason_id,omitempty"`
	StopId         string        `protobuf:"bytes,5,opt,name=stop_id,json=stopId,proto3" json:"stop_id,omitempty"`
	StopSequence   int32         `protobuf:"varint,6,opt,name=stop_sequence,json=stopSequence,proto3" json:"stop_sequence,omitempty"`
	Coord          *Bus_Coord    `protobuf:"bytes,7,opt,name=coord,proto3" json:"coord,omitempty"`
	Speed          float32       `protobuf:"fixed32,8,opt,name=speed,proto3" json:"speed,omitempty"`
	Azimuth        float32       `protobuf:"fixed32,9,opt,name=azimuth,proto3" json:"azimuth,omitempty"`
	ApproachStatsu int32         `protobuf:"varint,10,opt,name=approach_statsu,json=approachStatsu,proto3" json:"approach_statsu,omitempty"`
	Services       []*BusService `protobuf:"bytes,11,rep,name=services,proto3" json:"services,omitempty"`
	Demands        []int32       `protobuf:"varint,12,rep,packed,name=demands,proto3" json:"demands,omitempty"`
}

func (x *Bus) Reset() {
	*x = Bus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bus_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bus) ProtoMessage() {}

func (x *Bus) ProtoReflect() protoreflect.Message {
	mi := &file_bus_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bus.ProtoReflect.Descriptor instead.
func (*Bus) Descriptor() ([]byte, []int) {
	return file_bus_proto_rawDescGZIP(), []int{1}
}

func (x *Bus) GetBusId() string {
	if x != nil {
		return x.BusId
	}
	return ""
}

func (x *Bus) GetDelayTime() int32 {
	if x != nil {
		return x.DelayTime
	}
	return 0
}

func (x *Bus) GetServiceNum() int32 {
	if x != nil {
		return x.ServiceNum
	}
	return 0
}

func (x *Bus) GetReasonId() int32 {
	if x != nil {
		return x.ReasonId
	}
	return 0
}

func (x *Bus) GetStopId() string {
	if x != nil {
		return x.StopId
	}
	return ""
}

func (x *Bus) GetStopSequence() int32 {
	if x != nil {
		return x.StopSequence
	}
	return 0
}

func (x *Bus) GetCoord() *Bus_Coord {
	if x != nil {
		return x.Coord
	}
	return nil
}

func (x *Bus) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *Bus) GetAzimuth() float32 {
	if x != nil {
		return x.Azimuth
	}
	return 0
}

func (x *Bus) GetApproachStatsu() int32 {
	if x != nil {
		return x.ApproachStatsu
	}
	return 0
}

func (x *Bus) GetServices() []*BusService {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *Bus) GetDemands() []int32 {
	if x != nil {
		return x.Demands
	}
	return nil
}

type BusService_ShareRideSerivce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Capacity       int32 `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	OccupiedSeats  int32 `protobuf:"varint,2,opt,name=occupied_seats,json=occupiedSeats,proto3" json:"occupied_seats,omitempty"`
	AvailableSeats int32 `protobuf:"varint,3,opt,name=available_seats,json=availableSeats,proto3" json:"available_seats,omitempty"`
	NonSmoking     bool  `protobuf:"varint,4,opt,name=non_smoking,json=nonSmoking,proto3" json:"non_smoking,omitempty"`
	PricePerKm     int32 `protobuf:"varint,5,opt,name=price_per_km,json=pricePerKm,proto3" json:"price_per_km,omitempty"`
}

func (x *BusService_ShareRideSerivce) Reset() {
	*x = BusService_ShareRideSerivce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bus_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BusService_ShareRideSerivce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusService_ShareRideSerivce) ProtoMessage() {}

func (x *BusService_ShareRideSerivce) ProtoReflect() protoreflect.Message {
	mi := &file_bus_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusService_ShareRideSerivce.ProtoReflect.Descriptor instead.
func (*BusService_ShareRideSerivce) Descriptor() ([]byte, []int) {
	return file_bus_proto_rawDescGZIP(), []int{0, 0}
}

func (x *BusService_ShareRideSerivce) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *BusService_ShareRideSerivce) GetOccupiedSeats() int32 {
	if x != nil {
		return x.OccupiedSeats
	}
	return 0
}

func (x *BusService_ShareRideSerivce) GetAvailableSeats() int32 {
	if x != nil {
		return x.AvailableSeats
	}
	return 0
}

func (x *BusService_ShareRideSerivce) GetNonSmoking() bool {
	if x != nil {
		return x.NonSmoking
	}
	return false
}

func (x *BusService_ShareRideSerivce) GetPricePerKm() int32 {
	if x != nil {
		return x.PricePerKm
	}
	return 0
}

type BusService_DeliverSerivce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item      string  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Unit      string  `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	Num       int32   `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
	Avail     int32   `protobuf:"varint,4,opt,name=avail,proto3" json:"avail,omitempty"`
	DemandIds []int64 `protobuf:"varint,5,rep,packed,name=demand_ids,json=demandIds,proto3" json:"demand_ids,omitempty"`
}

func (x *BusService_DeliverSerivce) Reset() {
	*x = BusService_DeliverSerivce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bus_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BusService_DeliverSerivce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusService_DeliverSerivce) ProtoMessage() {}

func (x *BusService_DeliverSerivce) ProtoReflect() protoreflect.Message {
	mi := &file_bus_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusService_DeliverSerivce.ProtoReflect.Descriptor instead.
func (*BusService_DeliverSerivce) Descriptor() ([]byte, []int) {
	return file_bus_proto_rawDescGZIP(), []int{0, 1}
}

func (x *BusService_DeliverSerivce) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

func (x *BusService_DeliverSerivce) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *BusService_DeliverSerivce) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *BusService_DeliverSerivce) GetAvail() int32 {
	if x != nil {
		return x.Avail
	}
	return 0
}

func (x *BusService_DeliverSerivce) GetDemandIds() []int64 {
	if x != nil {
		return x.DemandIds
	}
	return nil
}

type Bus_Coord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lat float32 `protobuf:"fixed32,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon float32 `protobuf:"fixed32,2,opt,name=lon,proto3" json:"lon,omitempty"`
}

func (x *Bus_Coord) Reset() {
	*x = Bus_Coord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bus_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bus_Coord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bus_Coord) ProtoMessage() {}

func (x *Bus_Coord) ProtoReflect() protoreflect.Message {
	mi := &file_bus_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bus_Coord.ProtoReflect.Descriptor instead.
func (*Bus_Coord) Descriptor() ([]byte, []int) {
	return file_bus_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Bus_Coord) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Bus_Coord) GetLon() float32 {
	if x != nil {
		return x.Lon
	}
	return 0
}

var File_bus_proto protoreflect.FileDescriptor

var file_bus_proto_rawDesc = []byte{
	0x0a, 0x09, 0x62, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x62, 0x75, 0x73, 0x22, 0xe8, 0x03, 0x0a, 0x0a, 0x42, 0x75, 0x73, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x0a, 0x73, 0x68, 0x61, 0x72, 0x65, 0x5f, 0x72,
	0x69, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x62, 0x75, 0x73, 0x2e, 0x42, 0x75, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x52, 0x69, 0x64, 0x65, 0x53, 0x65, 0x72, 0x69, 0x76, 0x63,
	0x65, 0x48, 0x00, 0x52, 0x09, 0x73, 0x68, 0x61, 0x72, 0x65, 0x52, 0x69, 0x64, 0x65, 0x12, 0x40,
	0x0a, 0x07, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x62, 0x75, 0x73, 0x2e, 0x42, 0x75, 0x73, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x53, 0x65,
	0x72, 0x69, 0x76, 0x63, 0x65, 0x48, 0x00, 0x52, 0x07, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72,
	0x1a, 0xc1, 0x01, 0x0a, 0x10, 0x53, 0x68, 0x61, 0x72, 0x65, 0x52, 0x69, 0x64, 0x65, 0x53, 0x65,
	0x72, 0x69, 0x76, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74,
	0x79, 0x12, 0x25, 0x0a, 0x0e, 0x6f, 0x63, 0x63, 0x75, 0x70, 0x69, 0x65, 0x64, 0x5f, 0x73, 0x65,
	0x61, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x6f, 0x63, 0x63, 0x75, 0x70,
	0x69, 0x65, 0x64, 0x53, 0x65, 0x61, 0x74, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x61, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x61, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0e, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x65, 0x61, 0x74,
	0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x6f, 0x6e, 0x5f, 0x73, 0x6d, 0x6f, 0x6b, 0x69, 0x6e, 0x67,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x6e, 0x6f, 0x6e, 0x53, 0x6d, 0x6f, 0x6b, 0x69,
	0x6e, 0x67, 0x12, 0x20, 0x0a, 0x0c, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x70, 0x65, 0x72, 0x5f,
	0x6b, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x63, 0x65, 0x50,
	0x65, 0x72, 0x4b, 0x6d, 0x1a, 0x7f, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x69, 0x76, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x6e,
	0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d,
	0x12, 0x14, 0x0a, 0x05, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x65, 0x6d, 0x61, 0x6e, 0x64,
	0x5f, 0x69, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x03, 0x52, 0x09, 0x64, 0x65, 0x6d, 0x61,
	0x6e, 0x64, 0x49, 0x64, 0x73, 0x42, 0x0a, 0x0a, 0x08, 0x66, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x22, 0xb6, 0x03, 0x0a, 0x03, 0x42, 0x75, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x62, 0x75, 0x73,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x75, 0x73, 0x49, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x75, 0x6d,
	0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x73, 0x74, 0x6f, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x74, 0x6f, 0x70, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x74, 0x6f, 0x70, 0x5f, 0x73,
	0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x73,
	0x74, 0x6f, 0x70, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x2a, 0x0a, 0x05, 0x63,
	0x6f, 0x6f, 0x72, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x62, 0x75, 0x73, 0x2e, 0x42, 0x75, 0x73, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64,
	0x52, 0x05, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x7a, 0x69, 0x6d, 0x75, 0x74, 0x68, 0x18, 0x09, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07,
	0x61, 0x7a, 0x69, 0x6d, 0x75, 0x74, 0x68, 0x12, 0x27, 0x0a, 0x0f, 0x61, 0x70, 0x70, 0x72, 0x6f,
	0x61, 0x63, 0x68, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x75, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0e, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x61, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x73, 0x75,
	0x12, 0x31, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x0b, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x62, 0x75, 0x73, 0x2e, 0x42,
	0x75, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x18, 0x0c,
	0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x64, 0x65, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x1a, 0x2b, 0x0a,
	0x05, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6c, 0x6f, 0x6e, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x52, 0x79, 0x6f, 0x67, 0x61, 0x54, 0x61,
	0x6b, 0x61, 0x6f, 0x55, 0x43, 0x4c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x62, 0x75, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bus_proto_rawDescOnce sync.Once
	file_bus_proto_rawDescData = file_bus_proto_rawDesc
)

func file_bus_proto_rawDescGZIP() []byte {
	file_bus_proto_rawDescOnce.Do(func() {
		file_bus_proto_rawDescData = protoimpl.X.CompressGZIP(file_bus_proto_rawDescData)
	})
	return file_bus_proto_rawDescData
}

var file_bus_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_bus_proto_goTypes = []interface{}{
	(*BusService)(nil),                  // 0: proto.bus.BusService
	(*Bus)(nil),                         // 1: proto.bus.Bus
	(*BusService_ShareRideSerivce)(nil), // 2: proto.bus.BusService.ShareRideSerivce
	(*BusService_DeliverSerivce)(nil),   // 3: proto.bus.BusService.DeliverSerivce
	(*Bus_Coord)(nil),                   // 4: proto.bus.Bus.Coord
}
var file_bus_proto_depIdxs = []int32{
	2, // 0: proto.bus.BusService.share_ride:type_name -> proto.bus.BusService.ShareRideSerivce
	3, // 1: proto.bus.BusService.deliver:type_name -> proto.bus.BusService.DeliverSerivce
	4, // 2: proto.bus.Bus.coord:type_name -> proto.bus.Bus.Coord
	0, // 3: proto.bus.Bus.services:type_name -> proto.bus.BusService
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_bus_proto_init() }
func file_bus_proto_init() {
	if File_bus_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bus_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BusService); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bus_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bus_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BusService_ShareRideSerivce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bus_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BusService_DeliverSerivce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bus_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bus_Coord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_bus_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*BusService_ShareRide)(nil),
		(*BusService_Deliver)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bus_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bus_proto_goTypes,
		DependencyIndexes: file_bus_proto_depIdxs,
		MessageInfos:      file_bus_proto_msgTypes,
	}.Build()
	File_bus_proto = out.File
	file_bus_proto_rawDesc = nil
	file_bus_proto_goTypes = nil
	file_bus_proto_depIdxs = nil
}
